### ISSUE TITLE
click on links close the article

### ISSUE THREAD

**Issue by lpoujade** [pierrerousseau/zero-feeds#15]
Hi,
I usually open in new tab links which i found in my feeds, but here it close the article; and I think it can be good to difference click on links and click in "the void".

en tout cas, merci bcp pour cette app, et pour son design engagé :smile:

**Comment by pierrerousseau** [comment]
Thanks for using it and for reporting the bug !

**Comment by pierrerousseau** [comment]
So, it was a long time ago, but I just tried it, and I cant reproduce this behavior, what browser are you using ? And where do you click, on the link title or on the "open and read now" button ?

**Comment by lpoujade** [comment]
It was on older firefox version, clicking on the article title.
I can't either reproduce it now, I tell you if I see this behaviour

**Comment by pierrerousseau** [comment]
Cool ! I love to solve bugs without doing anything :D
