### ISSUE TITLE
Bug when trying to import large .opml file

### ISSUE THREAD

**Issue by Julianoe** [pierrerousseau/zero-feeds#18]
I tried to import an opml file with ~200 sources (export from Feedly) but the app only imported 7 sources in two different categories. There was no error message or anything. It just skipped the 99% of my sources... is it a known behavior ?

**Comment by pierrerousseau** [comment]
thanks for your report, but zero-feeds will stop soon to be available in cozy (it's already out of the store). So I suggest you to stop to use it.

**Comment by Julianoe** [comment]
Thanks for the update. I did not know what to understand with the fact that the app was not in the store... i found it on the "App" page of the website, i was confused. I guess that means only the apps in the store should be used.
Good evening !
