### ISSUE TITLE
Ghost RSS feed doesn't look to work

### ISSUE THREAD

**Issue by frankrousseau** [pierrerousseau/zero-feeds#3]
Hello there,

  Thank you again for Cozy Feeds. When I want to save this RSS feed, it doesn't work:
https://blog.benj.me/tag/cozycloud/rss/

Do you have any idea about what's wrong?

**Comment by pierrerousseau** [comment]
It's a pb with self-signed certificate. It works now although I don't really feel good with the solution. I guess you are on the dev branch, so there is the update.
