### ISSUE TITLE
Can't parse feeds

### ISSUE THREAD

**Issue by srh-moulin** [pierrerousseau/zero-feeds#4]
Salut Pierre,

Je teste l'appli zero-feeds en mode @dev comme tu m'avais indiqué à la réunion Cozy.
J'ai ajouté un feed qui apparemment n'est pas bon puisque j'ai le message "Can't parse feeds, please check feed adress"
Mais en même temps on m'indique que j'ai 10 nouveaux posts à lire sur ce flux...
![2015-07-20_180713](https://cloud.githubusercontent.com/assets/13273024/8780696/ef919e06-2f0a-11e5-9a18-5a5f6efc3770.jpeg)

C'est ma première issue : as-tu besoin d'autres infos ?

Merci d'avance !
Sarah

**Comment by pierrerousseau** [comment]
Salut,

merci pour les tests :)

oui, il me faudrait l'adresse du flux pour que je puisse tester.

**Comment by srh-moulin** [comment]
Salut,

Oui évidemment !
Le voici : http://www.etpourquoipascoline.fr/feed/
<http://www.google.com/url?q=http%3A%2F%2Fwww.etpourquoipascoline.fr%2Ffeed%2F&sa=D&sntz=1&usg=AFQjCNHW8CIGSZ7jsnA9kvampVP_irMI5A>

Celui de Courrier International faisait "freezer" l'appli hier et
n"affichait aucune entrée non plus :
http://www.courrierinternational.com/feed/all/rss.xml

Et en consultant Zero-feed, je vois ce matin qu'aucun flux n'affiche de
nouvelles entrées...
Ah, et je suis hébergée par Cozy.

Merci pour ton aide !

2015-07-20 18:35 GMT+02:00 Pierre Rousseau <notifications@github.com>:

> Salut,
>
> merci pour les tests :)
>
> oui, il me faudrait l'adresse du flux pour que je puisse tester.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pierrerousseau/zero-feeds/issues/4#issuecomment-122942244>
> .
>



-- 
Sarah M.

**Comment by pierrerousseau** [comment]
il n'y a peut-être pas de nouvelles entrées :) Pour vérifier, tu peux aller dans settings et cocher la case "Show new and old links".

Pour courrier international, le flux contient beaucoup d'articles, donc il faut juste attendre. Je vais voir ce que je peux faire pour éviter le freeze.

Pour etpourquoipascoline c'est plus étonnant.

**Comment by srh-moulin** [comment]
Ok j'ai testé. aucun old links n'apparaît.
[image: Images intégrées 1]

Le 21 juillet 2015 09:26, Pierre Rousseau <notifications@github.com> a
écrit :

> il n'y a peut-être pas de nouvelles entrées :) Pour vérifier, tu peux
> aller dans settings et cocher la case "Show new and old links".
>
> Pour courrier international, le flux contient beaucoup d'articles, donc il
> faut juste attendre. Je vais voir ce que je peux faire pour éviter le
> freeze.
>
> Pour etpourquoipascoline c'est plus étonnant.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pierrerousseau/zero-feeds/issues/4#issuecomment-123197900>
> .
>



-- 
Sarah M.

**Comment by pierrerousseau** [comment]
Quand as-tu installé l'application ?

**Comment by srh-moulin** [comment]
La première date qui apparaît dans les Logs, c'est le 10 juillet.
Ce qui doit correspondre, vu que je l'ai fait quelques jours après le meet
up.

C'est la version 1.4.3.

2015-07-21 13:00 GMT+02:00 Pierre Rousseau <notifications@github.com>:

> Quand as-tu installé l'application ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pierrerousseau/zero-feeds/issues/4#issuecomment-123262589>
> .
>



-- 
Sarah M.

**Comment by pierrerousseau** [comment]
Ok, alors il faut commencer par mettre à jour (supprimer l'application et la réinstaller avec @dev).

Ensuite, est-ce que tu peux passer la souris sur le nom du feeds et vérifier l'adresse qui doit apparaître en bas à gauche du navigateur. Si tu ne vois rien, clique sur la petite croix rouge, il va mettre le feeds dans le formulaire d'ajout et tu verras l’adresse.

**Comment by srh-moulin** [comment]
C'est fait et tout est revenu à la normale : ce feed en particulier, mais
tous les autres aussi.

Vu que je suis en @dev, il faut que je la désinstalle complètement à chaque
fois que je veux le mettre à jour ? (Parce que je l'avais déjà installée en
@dev).

En tout cas, merci beaucoup !

Le 21 juillet 2015 14:05, Pierre Rousseau <notifications@github.com> a
écrit :

> Ok, alors il faut commencer par mettre à jour (supprimer l'application et
> la réinstaller avec @dev <https://github.com/dev>).
>
> Ensuite, est-ce que tu peux passer la souris sur le nom du feeds et
> vérifier l'adresse qui doit apparaître en bas à gauche du navigateur. Si tu
> ne vois rien, clique sur la petite croix rouge, il va mettre le feeds dans
> le formulaire d'ajout et tu verras l’adresse.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pierrerousseau/zero-feeds/issues/4#issuecomment-123284982>
> .
>



-- 
Sarah M.

**Comment by pierrerousseau** [comment]
Oui, mais je vais passer sur la branche normale demain (il faudra encore désinstaller et réinstaller, mais en passant par le store cozy).

etpourquoipascoline remarche ?

**Comment by srh-moulin** [comment]
oui c'est tout bon !

Je repasserai sur la branche normale demain alors :)

Le 21 juillet 2015 15:16, Pierre Rousseau <notifications@github.com> a
écrit :

> Oui, mais je vais passer sur la branche normale demain (il faudra encore
> désinstaller et réinstaller, mais en passant par le store cozy).
>
> etpourquoipascoline remarche ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pierrerousseau/zero-feeds/issues/4#issuecomment-123301215>
> .
>



-- 
Sarah M.

**Comment by pierrerousseau** [comment]
cool :)
