### ISSUE TITLE
Hiding/showin feeds of a tag performs a reload of all the feeds of the tag

### ISSUE THREAD

**Issue by ZeHiro** [pierrerousseau/zero-feeds#7]
This works at least for the "untagged" feeds, as I don't have tagged feeds. 
What to do : 

Hide feeds
Show feeds

Expected behaviour:
just show feeds

Observed behaviour : 
All the feeds of the group are reloaded

**Comment by pierrerousseau** [comment]
What do you call hide/show feeds ? Clicking on the tag name ?

**Comment by ZeHiro** [comment]
Clicking on the tag name (the arrow next to the tag name)

**Comment by pierrerousseau** [comment]
So it is the expected behavior :)

**Comment by ZeHiro** [comment]
OK. I close

**Comment by pierrerousseau** [comment]
Thanks for opening this issue and the other ones :)
